class QuestPackage:
    quest_id: int
    next_quest_id: int
    giver_type: int
    status: int
    awards: list
    targets: list
    name: str
    giver_name: str
    location_id: int
    location_type: int
    parent_system_id: int
    messages: list
    additional_NPC_name: str
    additional_message: str
