class PlayerStatistics:
    status: int
    level: int
    pirate_status: int
    police_status: int
    military_status: int
    miner_status: int
    trader_status: int
    voyager_status: int
    for_next_level: int