class PlayerSkills:
    level: int
    experience: int
    exp_for_next: int
    kinetic_weapons: int
    energy_weapons: int
    rocket_weapons: int
    mining: int
    repairing: int
    trading: int
    control: int
    piloting: int
    defending: int
    attacking: int
    tactics: int
    targeting: int
    electronics: int
    biocemistry: int
    mechanics: int
    cybernetics: int
    freeSkills: int
    exp_for_first_skill_level: int
    exp_skill_reduser_coef: float
    exp_skill_grow_coef: float
    max_skill: int
    