class ReachableSystem:
    id: int
    class_number: int
    x: float
    y: float
    current: bool
    line_to: int
    sector: int
    energy_for_jump: int
    planets: list
    static_objects: list