from python.BaseClass.Other.BaseTypeStr import BaseTypeStr
class PlanetClassStr(BaseTypeStr):
    data = [
    ["SUN",  1],
    ["WHITE_SUN",  2],
    ["RED_SUN",  3],
    ["GREEN_SUN",  4],
    ["BLUE_SUN",  5],
    ["EARTH", 11],
    ["MARS", 12],
    ["EARTH1", 13],
    ["MARS1", 14],
    ["MARS2", 15],
    ["MOON", 16],
    ["MOON1", 17],
    ["VENUS", 18],
    ["SATURN", 19],
    ["PLUTO", 20],
    ["ICE_PLANET", 21],
    ["WATER_PLANET", 22],
    ["MOON2", 23],
    ["JUPITER", 24],
    ["JUPITER1", 25],
    ["MERCURY", 26],
    ["NEPTUNE", 27],
    ["URANUS", 28],
    ]